#!/bin/bash

set -e

# Install prerequisites
if ! dpkg -s qtbase5-dev \
|| ! dpkg -s qtchooser \
|| ! dpkg -s qt5-qmake \
|| ! dpkg -s qtbase5-dev-tools \
|| ! dpkg -s libusb-1.0-0-dev \
|| ! dpkg -s libfftw3-dev \
|| ! dpkg -s libeigen3-dev; then
    sudo apt-get update
    sudo apt-get install -y qtbase5-dev
    sudo apt-get install -y qtchooser
    sudo apt-get install -y qt5-qmake
    sudo apt-get install -y qtbase5-dev-tools
    sudo apt-get install -y libusb-1.0-0-dev
    sudo apt-get install -y libfftw3-dev
    sudo apt-get install -y libeigen3-dev
else
    echo "Prerequesites are already installed.  Skipping step."
fi

# Move to /tmp so we don't leave junk in the user's folders
cd /tmp

# Clone the latest version of Labrador
rm -rf labrador
git clone --depth 1 https://github.com/espotek-org/labrador

# Set QT_SELECT so qtchooser picks the right version
export QT_SELECT=qt5

# Build labrador
cd labrador/Desktop_Interface
qmake
make
sudo make install
sudo ldconfig

# Cleanup
rm -rf labrador

echo "Labrador installation success!"
echo "To run the software, enter \"labrador\" into the terminal or open the app from the \"Education\" menu."
