#!/bin/bash

set -e

rm -rf AppDir
qmake APPIMAGE=1 CONFIG+=release PREFIX=/usr DEFINES+=GIT_HASH_SHORT=$(git rev-parse --short HEAD)
make -j$(nproc) ${CC:+CC=${CC}} ${CXX:+CXX=${CXX} LINK=${CXX}}
make INSTALL_ROOT=AppDir install ; find AppDir/


wget -N -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20250213-2/linuxdeploy-x86_64.AppImage"
wget -N -nv "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/1-alpha-20250213-1/linuxdeploy-plugin-qt-x86_64.AppImage"
wget -N -nv "https://github.com/darealshinji/linuxdeploy-plugin-checkrt/releases/download/r1/linuxdeploy-plugin-checkrt.sh"
chmod a+x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage linuxdeploy-plugin-checkrt.sh

unset QTDIR
unset QT_PLUGIN_PATH
export LD_LIBRARY_PATH=$(realpath AppDir/usr/lib)
export LINUXDEPLOY_OUTPUT_VERSION=$(git rev-parse --short HEAD)
./linuxdeploy-x86_64.AppImage --appdir=AppDir --plugin=qt --plugin=checkrt --plugin=udev --output=appimage
