#!/bin/bash

set -e

rm -rf AppDir
qmake CONFIG+=release PREFIX=/usr
make -j$(nproc)
make INSTALL_ROOT=AppDir install ; find AppDir/
cp -r build_linux/apprun-hooks AppDir/

ARCH="x86_64"
wget -N -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20250213-2/linuxdeploy-${ARCH}.AppImage"
wget -N -nv "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/1-alpha-20250213-1/linuxdeploy-plugin-qt-${ARCH}.AppImage"
wget -N -nv "https://github.com/darealshinji/linuxdeploy-plugin-checkrt/releases/download/r1/linuxdeploy-plugin-checkrt.sh"
chmod a+x linuxdeploy-${ARCH}.AppImage linuxdeploy-plugin-qt-${ARCH}.AppImage linuxdeploy-plugin-checkrt.sh

unset QTDIR
unset QT_PLUGIN_PATH
export LD_LIBRARY_PATH=$(realpath AppDir/usr/lib)
export LINUXDEPLOY_OUTPUT_VERSION=$(git rev-parse --short HEAD)
./linuxdeploy-${ARCH}.AppImage --appdir=AppDir --plugin=qt --plugin=checkrt --output=appimage
