name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.10.1'
          host: 'linux'
          target: 'android'
          arch: 'android_armv7'

      - name: Install SDK
        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-27" "build-tools;27.0.3"

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r15c
          add-to-path: false

      - name: Build Android package
        working-directory: Desktop_Interface
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          qmake
          make
          make INSTALL_ROOT=labrador install
          JAVA_HOME=${JAVA_HOME_8_X64} androiddeployqt --input android-libLabrador.so-deployment-settings.json --output labrador --release --verbose --gradle --android-platform android-27

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: Desktop_Interface/labrador/build/outputs/apk/labrador-release-unsigned.apk
          compression-level: 0
          if-no-files-found: error
