name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Install dependencies
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y software-properties-common
      #    sudo apt-get install -y libfftw3-dev qtbase5-dev libusb-1.0-0-dev libeigen3-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.10.1'
          host: 'linux'
          target: 'android'
          arch: 'android_armv7'

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r15c
          add-to-path: false

      - name: Build Android package
        working-directory: Desktop_Interface
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          qmake
          make
